# Generated by Django 4.1.13 on 2024-04-10 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtasks',
            name='project_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subTasks', to='authApp.projects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtasks',
            name='task_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subTasks', to='authApp.tasks'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='project_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='authApp.projects'),
            preserve_default=False,
        ),
    ]
