# Generated by Django 4.1.13 on 2024-04-10 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_subtasks_project_id_subtasks_task_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='subtasks',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
