# Generated by Django 4.1.13 on 2024-04-10 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_alter_projects_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ExpirationDate'),
        ),
        migrations.AddField(
            model_name='subtasks',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ExpirationDate'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ExpirationDate'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='CreationDate'),
        ),
    ]
