# Generated by Django 4.1.13 on 2024-04-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_projects_expiration_date_subtasks_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('En espera', 'En espera'), ('En progreso', 'En progreso'), ('Finalizada', 'Finalizada')], default=1, max_length=20, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtasks',
            name='status',
            field=models.CharField(choices=[('En espera', 'En espera'), ('En progreso', 'En progreso'), ('Finalizada', 'Finalizada')], default=1, max_length=20, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('En espera', 'En espera'), ('En progreso', 'En progreso'), ('Finalizada', 'Finalizada')], default=1, max_length=20, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
